load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")

package(
    default_visibility = ["//:all_packages"],
)

kt_jvm_library(
    name = "navigation",
    srcs = ["Navigator.kt"],
    deps = ["//src/leodenault/synced/app:page"],
)
