package(
    default_visibility = ["//:all_packages"],
)

filegroup(
    name = "aggregate_licenses",
    srcs = ["aggregate_licenses.py"],
)

filegroup(
    name = "deploy",
    srcs = ["deploy.sh"],
)
