load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")

package(
    default_visibility = ["//:all_packages"],
)

kt_jvm_library(
    name = "coroutines",
    srcs = ["CoroutineScopes.kt"],
    deps = ["//third_party/kotlin"],
)
